from typing import Callable, Protocol

from src.core.domain.broker.schemas import MessageSchema


class BrokerProtocol(Protocol):
    async def setup_connection(self) -> None: ...

    async def setup_consumer(self, queue_name: str, handler: Callable) -> None: ...

    async def publish(self, message: MessageSchema, queue_name:str) -> None: ...

    async def consume(self) -> None: ...

    async def close(self) -> None: ...
